# Welcome to Jekyll! Config optimized for cybersecurity and CTF content

# Theme Settings
remote_theme             : "mmistakes/minimal-mistakes@4.15.1"
minimal_mistakes_skin    : "haxor"

# Site Settings
locale                   : "en-US"
title                    : "p1r4t3h00k.io"
title_separator          : "-"
name                     : "Snowscan"
description              : "Posts about security, CTFs, and networking"
url                      : "https://snowscan.io"
baseurl                  :
repository               : "slemire/slemire.github.io"
logo                     : "/assets/images/masthead.png"
breadcrumbs              : true
words_per_minute         : 200
comments:
  provider               : false

# SEO and Social Sharing
social:
  type                   : "Person"
  links:
    - "https://github.com/gabrie1Hz"
    - "https://www.youtube.com/@P1r4t3h00k"
    - "https://www.linkedin.com/in/gabriel-hernandez-3138132b8"

# Analytics
analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-145129883-1"

# Site Author
author:
  name                   : "P1r4t3h00k"
  avatar                 : "/assets/images/avatar.png"
  bio                    : "Ingeniero en sistemas, CTF player<br>HackTheBox"
  location               : "Mexico"
  email                  : "s4vitar11@gmail.com"
  github                 : "gabrie1Hz"
  youtube                : "https://www.youtube.com/@P1r4t3h00k"
  linkedin               : "gabriel-hernandez-3138132b8"

# Conversion and Markdown Processing
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives and Permalinks
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
permalink: /:title/
paginate: 10
paginate_path: /page:num/

# Output Compression and Defaults
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
